#BESU_RPC_HTTP_AUTHENTICATION_CREDENTIALS_FILE=/home/me/me_node/auth.toml
#make hash of password using 
# besu password hash --password=myPassword123

[Users.username1]
password = "$2a$10$vRrxNrOc4PVbL4JUGaZwXux4LNb.iKRWuV/sBt15y6OS0sfkDaKCG"
permissions=["net:*","eth:blockNumber"]

[Users.freighttrust0]
password = "$2a$10$NJHAGdFbWYD6o3DjjzYo3OclA.MYqkxN1nCpSgDKpsUHIq6RlW.CS"
permissions=["net:version","admin:*"]

[Users.freighttrust1]
password = "$2a$10$BmHT2JhEOCqSWJqWHPUjNeIY1QxWKneBjR9fr.tE3pBJDKAtCx66u"
permissions=["net:*","admin:*"]